default_install_hook_types:
  - commit-msg
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: goimports
        name: goimports
        entry: mise exec -- goimports -w
        language: system
        types:
          - go

      - id: commitizen
        name: commitizen
        entry: mise exec -- cz check --commit-msg-file
        language: system
        stages:
          - commit-msg

      - id: trufflehog
        name: trufflehog
        description: Detect secrets in your data with TruffleHog.
        entry: mise exec -- trufflehog git file://. --since-commit HEAD --results=verified --fail
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: trim-trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
